<?php
// Variables
return [
  "creatorName" => "Worknest Core",
  "creatorUrl" => "https://digifrica.com",
  "supportNumber" => "+256 700 100001",
  "supportWhatsappURL" => "https://wa.me/+256700100001",
  "supportEmail" => "info@digifrica.com",
  "templateName" => "Worknest Core",
  "templateFullName" => "Worknest Core",
  "templateSuffix" => "",
  "templateVersion" => "4.0.0",
  "templateFree" => false,
  "templateDescription" => "AI-Driven HRMS for Modern Businesses.",
  "templateKeyword" => "HRMS, HR, Management, System, Application, Software, Employee, Leave, Attendance, Payroll, Recruitment, Performance, Appraisal, Training, Development, Expense, Management, Task, Project, Team, Collaboration, Communication, Notification, Workflow, Automation, Reporting, Analytics, Dashboard, Admin, Panel",
  "licenseUrl" => "https://digifrica.com/license/",
  "livePreview" => "https://digifrica.com",
  "productPage" => "https://digifrica.com",
  "support" => "https://digifrica.com/support/",
  "moreThemes" => "https://digifrica.com",
  "documentation" => "https://digifrica.com",
  "changelog" => "https://digifrica.com",
  "repository" => "https://digifrica.com",
  "gitRepo" => "https://digifrica.com",
  "gitRepoAccess" => "https://digifrica.com",
  "githubFreeUrl" => "https://digifrica.com",
  "facebookUrl" => "https://digifrica.com",
  "twitterUrl" => "https://digifrica.com",
  "githubUrl" => "https://digifrica.com",
  "dribbbleUrl" => "https://digifrica.com",
  "instagramUrl" => "https://www.instagram.com/digifrica/",
  'linkedInUrl' => 'https://in.linkedin.com/company/cz-app-studio',
  'youtubeUrl' => 'https://www.youtube.com/@CZAppStudio',
  'appDemoLink' => 'https://drive.google.com/file/d/1gJl6YCoMzctQU47YNYIgKKTNeNg1s72t/view?usp=sharing',
  'superAdminPanelDemoLink' => 'https://opencorehr.digifrica.com/',
  'adminPanelDemoLink' => 'https://gpsfieldmanager.digifrica.com/'
];
